-- migration_v40_db_hardening.sql
-- Generated by Batch 15A audit
-- Date: 2026-06-22
-- Fixes: 3 CRITICAL, 6 HIGH findings

-- ============================================================
-- FIX 1: app_settings missing write policy — anyone can INSERT/UPDATE/DELETE
-- ============================================================
-- Finding: app_settings has RLS enabled but only a SELECT policy (USING true).
--   No INSERT/UPDATE/DELETE policies exist. With no write policy, PostgREST blocks
--   all writes (good), but add explicit admin-only policy for defense in depth.
-- Severity: HIGH
-- Affected: app_settings table

DROP POLICY IF EXISTS "Admins can write app_settings" ON public.app_settings;
CREATE POLICY "Admins can write app_settings"
  ON public.app_settings
  FOR ALL
  TO authenticated
  USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
  );

-- ============================================================
-- FIX 2: approve_channel_content / reject_channel_content missing status pre-check
-- ============================================================
-- Finding: approve_channel_content does not verify the post is currently in
--   'pending' status before approving. An admin could re-approve a rejected post
--   or double-approve. Same for reject. Add AND status = 'pending' guard.
-- Severity: HIGH
-- Affected: approve_channel_content, reject_channel_content functions

CREATE OR REPLACE FUNCTION public.approve_channel_content(content_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true) THEN
    RAISE EXCEPTION 'Access denied: admin only';
  END IF;

  UPDATE public.channel_posts
  SET status = 'approved',
      approved_at = now(),
      approved_by = auth.uid(),
      rejection_note = null
  WHERE id = content_id
    AND status = 'pending';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Content not found or not in pending state';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.reject_channel_content(content_id uuid, reason text DEFAULT NULL)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true) THEN
    RAISE EXCEPTION 'Access denied: admin only';
  END IF;

  UPDATE public.channel_posts
  SET status = 'rejected',
      approved_at = now(),
      approved_by = auth.uid(),
      rejection_note = reason
  WHERE id = content_id
    AND status = 'pending';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Content not found or not in pending state';
  END IF;
END;
$$;

-- ============================================================
-- FIX 3: record_post_view only increments approved posts
-- ============================================================
-- Finding: record_post_view increments view_count on ANY post regardless of status.
--   Should only count views on approved (visible) posts.
-- Severity: HIGH
-- Affected: record_post_view function

CREATE OR REPLACE FUNCTION public.record_post_view(p_post_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF p_post_id IS NULL THEN
    RETURN;
  END IF;
  UPDATE public.channel_posts
    SET view_count = view_count + 1
    WHERE id = p_post_id
      AND status = 'approved';
END;
$$;

-- ============================================================
-- FIX 4: activate_approved_channels missing search_path + grants to PUBLIC
-- ============================================================
-- Finding: SECURITY DEFINER without SET search_path (search_path hijack vector).
--   Also no explicit GRANT so defaults to PUBLIC. Fix both.
-- Severity: CRITICAL
-- Affected: activate_approved_channels function

CREATE OR REPLACE FUNCTION public.activate_approved_channels()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  UPDATE public.channels
  SET status = 'active'
  WHERE status = 'pending'
    AND approval_expires_at IS NOT NULL
    AND approval_expires_at <= now();
END;
$$;

REVOKE EXECUTE ON FUNCTION public.activate_approved_channels() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.activate_approved_channels() TO authenticated;

-- ============================================================
-- FIX 5: increment_channel_members missing search_path + no auth check
-- ============================================================
-- Finding: SECURITY DEFINER with no auth.uid() check and no SET search_path.
--   Any user could inflate any channel's member_count.
-- Severity: CRITICAL
-- Affected: increment_channel_members function

CREATE OR REPLACE FUNCTION public.increment_channel_members(p_channel_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Authentication required' USING errcode = '42501';
  END IF;
  UPDATE public.channels
  SET member_count = member_count + 1
  WHERE id = p_channel_id;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.increment_channel_members(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.increment_channel_members(uuid) TO authenticated;

-- ============================================================
-- FIX 6: handle_new_user trigger function missing SET search_path
-- ============================================================
-- Finding: SECURITY DEFINER without SET search_path — search_path hijack vector.
-- Severity: CRITICAL
-- Affected: handle_new_user trigger function

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, username)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
    LOWER(TRIM(split_part(NEW.email, '@', 1)))
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

-- ============================================================
-- FIX 7: handle_updated_at trigger function missing SET search_path
-- ============================================================
-- Finding: Should have safe search_path to prevent injection.
-- Severity: HIGH
-- Affected: handle_updated_at trigger function

CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- ============================================================
-- FIX 8: update_channel_post_count trigger function missing SET search_path
-- ============================================================
-- Finding: SECURITY DEFINER with no SET search_path.
-- Severity: HIGH
-- Affected: update_channel_post_count trigger function

CREATE OR REPLACE FUNCTION public.update_channel_post_count()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.status = 'approved' AND OLD.status != 'approved' THEN
    UPDATE public.channels SET post_count = post_count + 1 WHERE id = NEW.channel_id;
  END IF;
  RETURN NEW;
END;
$$;

-- ============================================================
-- FIX 9: Comprehensive GRANT tightening — revoke PUBLIC/anon from all RPCs
-- ============================================================
-- Finding: Functions created without explicit GRANT default to PUBLIC (which
--   includes anon). Even though they have internal auth checks, belt-and-suspenders
--   demands revoking anon access at the GRANT level too.
-- Severity: HIGH
-- Affected: all public RPCs
-- Implementation: Dynamic loop checks pg_proc so missing functions are skipped
--   (idempotent — safe to re-run, works even if some RPCs don't exist yet).

DO $$
DECLARE
  fn_specs TEXT[] := ARRAY[
    'activate_approved_channels:0',
    'increment_channel_members:1',
    'handle_new_user:0',
    'handle_updated_at:0',
    'update_channel_post_count:0',
    'approve_channel_content:1',
    'reject_channel_content:2',
    'record_post_view:1',
    'admin_list_channel_activity:0',
    'admin_list_pending_content:0',
    'is_owner_or_admin:1',
    'can_post_to_channel:1',
    'export_my_data:0',
    'get_my_subscription_status:0',
    'get_my_channel_posts:1',
    'join_channel:1',
    'leave_channel:1',
    'update_channel:3',
    'delete_channel:1',
    'approve_post:1',
    'reject_post:2',
    'approve_subscription_request:1',
    'reject_subscription_request:2',
    'increment_storage_used:2',
    'decrement_storage_used:2'
  ];
  fn_spec TEXT;
  fn_name TEXT;
  fn_args INT;
  fn_oid OID;
  fn_sig TEXT;
BEGIN
  FOREACH fn_spec IN ARRAY fn_specs LOOP
    fn_name := split_part(fn_spec, ':', 1);
    fn_args := split_part(fn_spec, ':', 2)::INT;

    SELECT p.oid, pg_get_function_identity_arguments(p.oid)
      INTO fn_oid, fn_sig
      FROM pg_proc p
      JOIN pg_namespace n ON p.pronamespace = n.oid
     WHERE n.nspname = 'public'
       AND p.proname = fn_name
       AND p.pronargs = fn_args
     LIMIT 1;

    IF fn_oid IS NOT NULL THEN
      EXECUTE format('REVOKE ALL ON FUNCTION public.%I(%s) FROM PUBLIC', fn_name, fn_sig);
      EXECUTE format('REVOKE ALL ON FUNCTION public.%I(%s) FROM anon', fn_name, fn_sig);
      EXECUTE format('GRANT EXECUTE ON FUNCTION public.%I(%s) TO authenticated', fn_name, fn_sig);
      RAISE NOTICE 'secured: %(%)', fn_name, fn_sig;
    ELSE
      RAISE NOTICE 'skipped (not found): % (args=%)', fn_name, fn_args;
    END IF;

    fn_oid := NULL;
    fn_sig := NULL;
  END LOOP;
END $$;

-- ============================================================
-- Reload PostgREST schema cache
-- ============================================================
NOTIFY pgrst, 'reload schema';
